# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Page.create(title: 'Home', content:"")
Page.create(title: 'Staff', content:"")
Page.create(title: 'EOC', content:"")
Page.create(title: 'Pictures', content:"")
Page.create(title: 'External Links', content:"")
Page.create(title: 'Latest News', content:"")
Hazard.create(title: 'Earthquake', content:"", category:"Natural Hazards")
Hazard.create(title: 'Thunderstorm', content:"", category:"Natural Hazards")
Hazard.create(title: 'Tornado', content:"", category:"Natural Hazards")
Hazard.create(title: 'Fire', content:"", category:"Natural Hazards")
Hazard.create(title: 'Flood', content:"", category:"Natural Hazards")
Hazard.create(title: 'Winter Storm', content:"", category:"Natural Hazards")
Hazard.create(title: 'Wildfire', content:"", category:"Natural Hazards")
Hazard.create(title: 'Extreme Heat', content:"", category:"Natural Hazards")
Hazard.create(title: 'Nuclear', content:"", category:"Technological Hazards")
Hazard.create(title: 'Dam Failure', content:"", category:"Technological Hazards")
Hazard.create(title: 'Hazardous Materials', content:"", category:"Technological Hazards")
Hazard.create(title: 'Biological Threats', content:"", category:"Terrorism")
Hazard.create(title: 'Bomb Threat', content:"", category:"Terrorism")
Hazard.create(title: 'Chemical Threats', content:"", category:"Terrorism")
Hazard.create(title: 'Explosions', content:"", category:"Terrorism")
Hazard.create(title: 'Nuclear Blast', content:"", category:"Terrorism")
Hazard.create(title: 'Radiological Dispersion Device', content:"", category:"Terrorism")
Hazard.create(title: 'Suspicious Packages and Letters', content:"", category:"Terrorism")
